# Generated by Django 4.1.1 on 2022-09-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_booknote_book_alter_booknote_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktracker',
            name='status',
            field=models.CharField(choices=[('rg', 'Reading'), ('rd', 'Read'), ('ur', 'Unread')], default='ur', max_length=100),
        ),
    ]
